server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://root:123@192.168.2.101:27017
      database: xc_cms
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 192.168.2.101
    port: 5672
    username: guest
    password: guest
    virtualHost: /
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://192.168.2.101:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:192.168.2.101}
    #instance-id: ${spring.application.name}:${server.port} #指定实例id
cms:
  ip: 127.0.0.115534345
    