spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/shop_order?serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true&characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）


mybatis-plus:
  global-config:
    db-config:
      # 如果删除状态 值为1
      logic-delete-value: 1
      # 未删除 0
      logic-not-delete-value: 0
http:
  maxTotal: 40000
  defaultMaxPerRoute: 40000
  connectTimeout: 100
  connectionRequestTimeout: 500
  socketTimeout: 1000
  staleConnectionCheckEnabled: true
