server:
  port: 31200
spring:
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 50MB
      # 最大支持请求大小
      max-request-size: 50MB